src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $uuid;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $nickname;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Post", mappedBy="user")
     */
    private $post;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Category", mappedBy="user")
     */
    private $category;

    /**
     * @ORM\Column(type="string", nullable=true)
     */
    private $profile_image;

    public function __construct()
    {
        
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(): self
    {
        $this->uuid = uniqid('User_');

        return $this;
    }

    public function getNickname(): ?string
    {
        return $this->nickname;
    }

    public function setNickname(string $nickname): self
    {
        $this->nickname = $nickname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getProfileImage(): ?string
    {
        return $this->profile_image;
    }

    public function setProfileImage(string $image_name): self
    {
        $this->profile_image = $image_name;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Doctrine\DBAL\Types\TextType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\PasswordType;
use Symfony\Component\Form\Extension\Core\Type\RepeatedType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('nickname')
        ->add('password',  RepeatedType::class, [
            'type' => PasswordType::class,
            'invalid_message' => 'The password fields must match.',
            'options' => ['attr' => ['class' => 'password-field']],
            'required' => true,
            'first_options'  => ['label' => 'Password'],
            'second_options' => ['label' => 'Repeat Password']
        ])
        ->add('email', EmailType::class, [
            'required' => true
        ])
        ->add('profile_image', FileType::class, [
            'required' => false,
            "label" => "Imagen:",
            "attr" =>array("class" => "form-control"),
            "data_class" => null
        ])
        ->add('register', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\PostRepository;
use App\Repository\UserRepository;
use App\Services\FileUploader;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UserController extends AbstractController
{
    private $repository;

    public function __construct(UserRepository $userRepository) 
    {
        $this->repository = $userRepository;
    }

    public function index()
    {
        return $this->render('user/index.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }

    public function show(int $id, PostRepository $postRepository)
    {
        $user = $this->repository->find($id);
        // WATCH! Another solution could be better  
        $user_posts = $postRepository->findBy(['user' => $id]);
        return $this->render('user/profile.html.twig', [
            'user' => $user,
            'posts' => $user_posts
        ]);
    }

    public function register(
        Request $request, 
        UserPasswordEncoderInterface $passwordEncoder, 
        FileUploader $fileUploader)
    {
        $newUser = new User();
        $newUser->setUuid();
        
        $form = $this->createForm(UserType::class, $newUser);

        $form->handleRequest($request);
        
        if($form->isSubmitted() && $form->isValid()) {
            $user = $form->getData();
            $em = $this->getDoctrine()->getManager();

            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );

            /* @var UploadedFile $file */
            $file = $request->files->get('user')['profile_image'];

            if($file) {
                $filename = $fileUploader->updateFile($file, 'images');
                $user->setProfileImage($filename);
            }

            $em->persist($user);
            $em->flush();

            return $this->redirectToRoute('app_login') ;
        }

        return $this->render('user/register.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    public function update(Request $request, int $id, UserPasswordEncoderInterface $passwordEncoder, FileUploader $fileUploader)
    {
        $user = $this->repository->find($id);
        
        $form = $this->createForm(UserType::class, $user);

        $form->handleRequest($request);
                
        if($form->isSubmitted() && $form->isValid()) {
            $user = $form->getData();
            $em = $this->getDoctrine()->getManager();

            $user->setPassword(
                $passwordEncoder->encodePassword(
                    $user,
                    $form->get('password')->getData()
                )
            );

            /* @var UploadedFile $file */
            $file = $request->files->get('user')['profile_image'];

            if($file) {
                $filename = $fileUploader->updateFile($file, 'images');
                $user->setProfileImage($filename);
            }

            $em->persist($user);
            $em->flush();

            $this->addFlash('success', 'User updated!');


            return $this->redirectToRoute('user.profile', ['id' => $id]) ;
        }

        return $this->render('user/update.html.twig', [
            'form' => $form->createView(),
            'user' => $user
        ]);
    }
}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Profile{% endblock %}

{% block body %}
user index = profile
{% endblock %}

templates/user/profile.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="row mt-4">
    
        <div class="col-8">
            
            {% for post in posts %}
                <div class="p-3 row border  rounded mt-2">
                    <div class="col-3">

                        <img class="img-thumbnail mt-2" 
                        {% if post.imagename is null %}
                        src="{{asset('/default/track-img.jpg')}}" alt="default image"
                        {% else %}
                        src="{{asset('/uploads/images/' ~ post.imagename )}}" alt="{{post.name}}"
                        {% endif %}
                        >

                    </div>
                    <div class="col-9 ">
                        
                        <div class="col-12 mt-2">

                            <p class="h4">
                                {{post.name}} 
                            </p>
                            <p class="h6">
                                {{post.description}}
                            </p>
                            {% if post.user is null %} 
                            {% else %}
                            <p class="h6">
                                <em><small>{{post.createdAt|date()}} </small></em>
                            </p>
                            {% endif %}

                        </div>
                  
                        <audio class="w-100" controls class="" width="300" height="32" >
                            <source src="{{asset('uploads/audio/') ~ post.trackname }}">
                        </audio>

                    </div>

                </div>
            {% endfor %}
        </div>
        <div class="col-4 text-right">
            <img class="img-thumbnail " src="{{asset('uploads/images/' ~ user.profileImage)}}">
            <div class="p-3 ">
                <h3>{{user.nickname}}</h3>
                <h6>{{user.email}}</h6>

                {% if app.user == user %}
                <a role="button" class="btn btn-sm btn-secondary mb-3" href="{{path('user.update', {id: user.id})}}">Edit profile</a>

                <a role="button" class="btn btn-sm btn-danger mb-3" href="{{path('app_logout')}}">Log out</a>
            
                {% endif %}
            </div>
        </div>
    </div>
    

{% endblock %}

templates/user/register.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello UserController!{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-4">
        </div>
        <div class="col-4">
        {{form(form)}}
        <p> back to <a href="{{path('app_login')}}">log in</a> </p> 
        </div>
        <div class="col-4">
        </div>
    </div>
{% endblock %}

templates/user/update.html.twig
{% extends 'base.html.twig' %}

{% block title %}Update user{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-4">
        </div>
        <div class="col-4">
        {{form(form)}}
        <p> back to <a href="{{path('user.profile', {id: user.id})}}">profile</a> </p> 
        </div>
        <div class="col-4">
        </div>
    </div>
{% endblock %}